# Generated by Django 4.0.6 on 2022-07-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Blog Kategoriya',
                'verbose_name_plural': 'Blog Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='CategoryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Ish Kategoriya',
                'verbose_name_plural': 'Ish Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=55)),
                ('text', models.TextField()),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=55)),
                ('images', models.ImageField(upload_to='work_images')),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('category_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categorywork')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('text', models.TextField()),
                ('images', models.ImageField(upload_to='images')),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('category_blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoryblog')),
            ],
        ),
    ]
